### ISSUE TITLE
include PDF

### ISSUE THREAD

**Issue by christian-steinmeyer** [rlupton20/yampaTutorial#2]
Hi! It would be really cool to have a built PDF along with the README to be able to look into it without running through download -> compile ( -> possible problems while doing so, e.g. fonts etc.)

Thanks in advance! :)

**Comment by rlupton20** [comment]
For the moment I've added the pdf to the github repository. You should be able to download it from there.

Bear in mind these are mostly notes to myself, calling it a tutorial might be a bit far fetched. Still, it might be enough to get you running some code, while not requiring some odd robot simulator or similar (which was really the purpose). From what I recall I stalled a little because I wanted reactimate to be monadic, which is currently an issue over at Yampa.

I might get round to working this into something more presentable in the future, but for the moment I have some other projects I would prefer to be working on. In any case feedback is welcome!

**Comment by christian-steinmeyer** [comment]
Thanks!

**Comment by christian-steinmeyer** [comment]
It looks like you did a great job! The beginning is especially great, because you seem to start somewhere people can relate to (opposed to some other sources out there). And I also like that you keep giving examples (that are not just pure abstraction). You should mention somehow / somewhere that and from where you gathered your information that you didn't come up with yourself. But other than that, great! 

In case you ever get to work on it again - more examples would be great. Just simple programs, but actual programs with some real application say math problems, simple animation, user interaction... doesn't matter - the important thing is, that you provide code that is well written (as you do so far) and that the scenarios are easily understood. Most things you can find online are mostly papers or poorly written guides with at most a couple of lines for a concept and then you're supposed to just _know it_...

Thanks again. I believe it already helped me and probably will do so even more, next time I sit down with a little bit of time and continue learning Yampa. Greetings :)

**Comment by rlupton20** [comment]
Well, that is encouraging! Since people seem to come across this and want to read it, I might give it some love in the near future (i have a week off work next week, but an already ambitious pile of todos). I'll take what you've said into account, and try to focus on small working examples. Let me know if there is anything out there (in other 'guides') you would like better explained, or examples for, and I'll see if I can conjure something up. More than anything, thanks for the feedback!

First I have to get my TeX distribution up and running again, and endure the pain of building my own TeX :P.
